on: [push]

jobs:
  sync-configs:
    runs-on: ubuntu-latest
    name: Test 123
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync configs
        id: hello
        uses: captncraig/fleetcmdr@v5
        with:
          host: https://fleet-management-dev-001.grafana-dev.net
          user: 2747
          token: ${{ secrets.FLEET_TOKEN }}
